//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Posta
{
    using System;
    using System.Collections.Generic;
    
    public partial class DK_Posiljka_dgv
    {
        public int Id { get; set; }
        public bool Isporuceno { get; set; }
        public string Polaziste { get; set; }
        public string Odrediste { get; set; }
        public string Primatelj { get; set; }
        public string Posiljatelj { get; set; }
    }
}
