//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Posta
{
    using System;
    using System.Collections.Generic;
    
    public partial class DK_Posiljka
    {
        public int Id { get; set; }
        public string Posiljatelj { get; set; }
        public string Primatelj { get; set; }
        public int Polaziste_ID { get; set; }
        public int Odrediste_ID { get; set; }
        public int Trenutno_ID { get; set; }
        public bool Isporuceno { get; set; }
    
        public virtual DK_Gradovi DK_Gradovi { get; set; }
        public virtual DK_Gradovi DK_Gradovi1 { get; set; }
        public virtual DK_Gradovi DK_Gradovi2 { get; set; }
    }
}
