//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Posta
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PostaEntities1 : DbContext
    {
        public PostaEntities1()
            : base("name=PostaEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DK_Gradovi> DK_Gradovi { get; set; }
        public virtual DbSet<DK_Posiljka> DK_Posiljka { get; set; }
        public virtual DbSet<DK_Posiljka_dgv> DK_Posiljka_dgv { get; set; }
    }
}
